import { defineConfig } from "tsup";

export default defineConfig({
  clean: true,
  dts: true,
  entry: [
    "src/index.ts",
    "src/s3/index.ts",
    "src/r2/index.ts",
    "src/vercel-blob/index.ts",
    "src/netlify-blobs/index.ts",
    "src/minio/index.ts",
    "src/digitalocean-spaces/index.ts",
    "src/storj/index.ts",
    "src/hetzner/index.ts",
    "src/akamai/index.ts",
    "src/gcs/index.ts",
    "src/google-drive/index.ts",
    "src/azure/index.ts",
    "src/supabase/index.ts",
    "src/fs/index.ts",
    "src/uploadthing/index.ts",
    "src/onedrive/index.ts",
    "src/dropbox/index.ts",
    "src/box/index.ts",
    "src/ai-sdk/index.ts",
  ],
  format: ["esm"],
  sourcemap: true,
  splitting: false,
  target: "es2022",
  treeshake: true,
});
